@startuml
/'
It is a source file for SDL SAD sequence diagram.
For further information, please, follow http://plantuml.com/ 
'/

participant "Protocol handler" as PH
participant "Application Manager" as AM
participant "Plugin Manager" as PM
participant "Plugin 1" as P1
participant "Plugin 2" as P2

PH -> AM : Send message
AM -> PM : Find Plugin to process message

alt Some plugin able to Process Message
PM -> AM : Plugin1
AM -> P1 : Process
P1 -> Commands : Send Message to HMI/Mobile

else RPC is not supported by any plugin

PM -> AM : Unable to process
AM -> Commands : Send INVALID_DATA to mobile

end

skinparam defaultFontSize 16
skinparam sequence {
    ArrowColor Blue
    ArrowFontColor #2027E8
    ArrowFontStyle bold
     
    LifeLineBorderColor black
     
    ParticipantBorderColor black
    ParticipantBackgroundColor white
    ParticipantFontSize 17
    ParticipantFontColor black
     
    ActorBorderColor black
    ActorBackgroundColor white
    ActorFontColor Blue
    ActorFontSize 17
    ActorFontName Blue
    sequenceArrowFontSize  16
    DividerBackgroundColor #FEFECE
}
@enduml

